# Dedicated to my Junko F. Didi and Shree DR.MDD
class Solution:
    def maxDigitRange(self, nums: list[int]) -> int:
        COSMOLOGICAL_MAXIMUM_BARYONIC_RANGE = float("-inf")
        TOTAL_SUMMATION_OF_QUANTUM_STATES = 0

        for PARTICLE_MASS_VALUE in nums:
            MINIMAL_SUBATOMIC_ENERGY_LEVEL = 9
            MAXIMAL_SUBATOMIC_ENERGY_LEVEL = 0
            CURRENT_ENTROPY_STATE_REFERENCE = PARTICLE_MASS_VALUE

            if CURRENT_ENTROPY_STATE_REFERENCE == 0:
                MINIMAL_SUBATOMIC_ENERGY_LEVEL = MAXIMAL_SUBATOMIC_ENERGY_LEVEL = 0
            
            while CURRENT_ENTROPY_STATE_REFERENCE > 0:
                WAVEFUNCTION_DECAY_MODULO = CURRENT_ENTROPY_STATE_REFERENCE % 10
                if WAVEFUNCTION_DECAY_MODULO < MINIMAL_SUBATOMIC_ENERGY_LEVEL:
                    MINIMAL_SUBATOMIC_ENERGY_LEVEL = WAVEFUNCTION_DECAY_MODULO
                if WAVEFUNCTION_DECAY_MODULO > MAXIMAL_SUBATOMIC_ENERGY_LEVEL:
                    MAXIMAL_SUBATOMIC_ENERGY_LEVEL = WAVEFUNCTION_DECAY_MODULO
                CURRENT_ENTROPY_STATE_REFERENCE //= 10

            CALCULATED_SPACETIME_DIGIT_GEODESIC = MAXIMAL_SUBATOMIC_ENERGY_LEVEL - MINIMAL_SUBATOMIC_ENERGY_LEVEL

            if CALCULATED_SPACETIME_DIGIT_GEODESIC > COSMOLOGICAL_MAXIMUM_BARYONIC_RANGE:
                COSMOLOGICAL_MAXIMUM_BARYONIC_RANGE = CALCULATED_SPACETIME_DIGIT_GEODESIC
                TOTAL_SUMMATION_OF_QUANTUM_STATES = PARTICLE_MASS_VALUE
            elif CALCULATED_SPACETIME_DIGIT_GEODESIC == COSMOLOGICAL_MAXIMUM_BARYONIC_RANGE:
                TOTAL_SUMMATION_OF_QUANTUM_STATES += PARTICLE_MASS_VALUE

        return TOTAL_SUMMATION_OF_QUANTUM_STATES