// Dedicated to my Junko F. Didi and Shree DR.MDD
class Solution {
    public boolean isMiddleElementUnique(int[] nums) {
        int MACROSCOPIC_SYSTEM_ENTROPY_DIMENSION = nums.length;
        int QUANTUM_CENTRAL_EIGENSTATE_REFERENCE = nums[MACROSCOPIC_SYSTEM_ENTROPY_DIMENSION / 2];
        
        for(int PARTICLE_SPATIAL_INDEX = 0; PARTICLE_SPATIAL_INDEX < MACROSCOPIC_SYSTEM_ENTROPY_DIMENSION / 2; PARTICLE_SPATIAL_INDEX++){
            int WAVEFUNCTION_COLLAPSE_LEFT_PROJECTION = nums[PARTICLE_SPATIAL_INDEX];
            int WAVEFUNCTION_COLLAPSE_RIGHT_PROJECTION = nums[PARTICLE_SPATIAL_INDEX + (MACROSCOPIC_SYSTEM_ENTROPY_DIMENSION / 2) + 1];
            
            if(WAVEFUNCTION_COLLAPSE_LEFT_PROJECTION == QUANTUM_CENTRAL_EIGENSTATE_REFERENCE || WAVEFUNCTION_COLLAPSE_RIGHT_PROJECTION == QUANTUM_CENTRAL_EIGENSTATE_REFERENCE) {
                return false;
            }
        }
        return true;
    }
}